name: Update README with Version

on:
  push:
    paths:
      - version.txt
      - README.md

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version.txt and update README.md
        run: |
          VERSION=$(cat version.txt)
          echo "Updating README.md with version: $VERSION"
          
          # Patikrinkite, ar README.md turi "Versija:" eilutę
          if grep -q "Versija:" README.md; then
            echo "Found 'Versija:' in README.md. Updating..."
            # Jei "Versija:" yra, atnaujinkite ją
            sed -i "s/Versija:.*/Versija: $VERSION/" README.md
          else
            echo "'Versija:' not found in README.md. Adding it..."
            # Jei "Versija:" nėra, pridėkite ją pabaigoje
            echo -e "\nVersija: $VERSION" >> README.md
          fi

      - name: Configure GitHub authentication
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global credential.helper store
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Čia nurodome, kad naudotume savo tokeną

      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "Update version in README.md"
          
          # Naudoti HTTPS su token autentifikacija
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
